[package]
name = "main-ui"
version = "0.1.0"
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
dioxus = { version = "0.6.0", features = ["router"] }

dioxus-aws = { version = "0.6.12" }
dioxus-web = { version = "0.6.0", features = [], optional = true }
dioxus-logger = { version = "0.5.0" }
tracing = { version = "0.1.40" }

wasm-bindgen = { version = "0.2.99", optional = true }
wasm-bindgen-futures = { version = "0.4.49", optional = true }
web-sys = { version = "0.3.72", features=["Navigator"], optional = true}
serde = "1.0.216"

[features]
default = []
web = ["web-sys", "wasm-bindgen", "wasm-bindgen-futures", "dioxus-aws/web", "dioxus-web"]
web-release = ["web", "dioxus-aws/web-release"]
server = ["dioxus-aws/server"]
lambda = ["server", "dioxus-aws/lambda"]
